LearningManagementSystem/Controllers/ActivityTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;

namespace LearningManagementSystem.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class ActivityTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ActivityTypes
        public ActionResult Index()
        {
            return View(db.ActivityTypes.ToList());
        }

        // GET: ActivityTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            return View(activityType);
        }

        // GET: ActivityTypes/Create
        [Authorize(Roles = "Teacher")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ActivityTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Create([Bind(Include = "ActivityTypeId,ActivityTypeName")] ActivityType activityType)
        {
            if (ModelState.IsValid)
            {
                db.ActivityTypes.Add(activityType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(activityType);
        }

        // GET: ActivityTypes/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            return View(activityType);
        }

        // POST: ActivityTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit([Bind(Include = "ActivityTypeId,ActivityTypeName")] ActivityType activityType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activityType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(activityType);
        }

        // GET: ActivityTypes/Delete/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            return View(activityType);
        }

        // POST: ActivityTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteConfirmed(int id)
        {
            ActivityType activityType = db.ActivityTypes.Find(id);
            db.ActivityTypes.Remove(activityType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningManagementSystem/Views/ActivityTypes/Create.cshtml
@model LearningManagementSystem.Models.ActivityType

@{
    ViewBag.Title = "Create";
}

<h2>Aktivitetstyp</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Skapa Aktivitetstyp</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ActivityTypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivityTypeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivityTypeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LearningManagementSystem/Views/ActivityTypes/Delete.cshtml
@model LearningManagementSystem.Models.ActivityType

@{
    ViewBag.Title = "Delete";
}

<h2>Aktivitetstyp</h2>

@*<h3>Are you sure you want to delete this?</h3>*@
<div>
    @*<h4>ActivityType</h4>*@
    <hr />
    <h4>Radera Aktivitetstyp</h4>
    <dl>
    @*<dl class="dl-horizontal">*@
        <dt>
            @Html.DisplayNameFor(model => model.ActivityTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityTypeName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Radera" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Tillbaka", "Index")
        </div>
    }
</div>

LearningManagementSystem/Views/ActivityTypes/Details.cshtml
@model LearningManagementSystem.Models.ActivityType

@{
    ViewBag.Title = "Details";
}


<h2>@Html.DisplayFor(model => model.ActivityTypeName)</h2>

<div>
    @*<h4>ActivityType</h4>*@
    <hr />
    <h4>@Html.DisplayFor(model => model.ActivityTypeName) </h4>
    <dl>
    @*<dl class="dl-horizontal">*@
        @*<dt>
            @Html.DisplayNameFor(model => model.ActivityTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityTypeName)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Redigera", "Edit", new { id = Model.ActivityTypeId }) |
    @Html.ActionLink("Tillbaka", "Index")
</p>

LearningManagementSystem/Views/ActivityTypes/Edit.cshtml
@model LearningManagementSystem.Models.ActivityType

@{
    ViewBag.Title = "Edit";
}

<h2>Aktivitetstyp</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
   <div> 
    @*<div class="form-horizontal">*@
        @*<h4>ActivityType</h4>*@
        <hr />
        <h4>Redigera Activitetstyp</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ActivityTypeId)

        <div class="form-group">
            @Html.LabelFor(model => model.ActivityTypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivityTypeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivityTypeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LearningManagementSystem/Views/ActivityTypes/Index.cshtml
@model IEnumerable<LearningManagementSystem.Models.ActivityType>

@{
    ViewBag.Title = "Index";
}

<h2>Aktivitetstyp</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<p>
    <input type="button" value="Skapa aktivitetstyp" class="btn btn-default btn-primary" onclick="location.href='@Url.Action("Create","ActivityTypes")' " />
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ActivityTypeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ActivityTypeName)
        </td>
        <td>
            @Html.ActionLink("Redigera", "Edit", new { id=item.ActivityTypeId }) |
            @Html.ActionLink("Detaljer", "Details", new { id=item.ActivityTypeId }) |
            @Html.ActionLink("Radera", "Delete", new { id=item.ActivityTypeId })
        </td>
    </tr>
}

</table>