LearningManagementSystem/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;

namespace LearningManagementSystem.Models
{
    [Authorize]
    public class CoursesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Courses
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Group);
            return View(db.Courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        public ActionResult CourseActivities(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Teacher")]
        public ActionResult Create()
        {
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "GroupName"); 
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Create([Bind(Include = "CourseId,CourseName,CourseDescription,CourseStart,CourseEnd,GroupId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "GroupName", course.GroupId);
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "GroupName", course.GroupId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit([Bind(Include = "CourseId,CourseName,CourseDescription,CourseStart,CourseEnd,GroupId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "GroupName", course.GroupId);
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningManagementSystem/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;
using System.IO;

namespace LearningManagementSystem.Controllers
{
    [Authorize(Roles="Teacher")]
    public class DocumentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //private const string localUrl = @"~\Uploads\" ;
        private const string localUrl = @"\Uploads\";

        // GET: Documents
        public ActionResult Index()
        {
            var documents = db.Documents.Include(d => d.Uploader);
            return View(documents.ToList());
        }

        // GET: Documents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // GET: Documents/Create
        public ActionResult Create(int? GrId)
        {
            TempData["GroupId"] = GrId;
            ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DocumentId,DocumentName,Description,FileName,FilePath,UploaderId,UploadDate,GroupId,CourseId,ActivityId")] Document document, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                 
                var CurrentUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();
                if (CurrentUser.GroupId != null)
                {
                    document.GroupId = CurrentUser.GroupId;
                }
                else if (TempData["GroupId"] != null)
                {
                    document.GroupId = (int)TempData["GroupId"];
                }
                else
                {
                    document.GroupId = null;
                }

                if (upload != null && upload.ContentLength > 0)
                {
                    // Här sparas filen som ska laddas upp i vår katalog
                    string nameOfFile = System.IO.Path.GetFileName(upload.FileName);
                    string saveFilePath = Path.Combine((Server.MapPath(@"~\Uploads\")), nameOfFile);
                    upload.SaveAs(saveFilePath);

                    /// Här laddar vi dbset<Documents> med korrekta värden.
                    document.UploadDate = DateTime.Now;
                    document.FileName = nameOfFile;
                    document.FilePath = (@localUrl + nameOfFile);
                    document.UploaderId = CurrentUser.Id;
                    db.Documents.Add(document);
                    db.SaveChanges();
                    //return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }

            ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName", document.UploaderId, document.GroupId);
            return View(document);
        }


        // GET: Documents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            //ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName", document.UploaderId);
            //Group group = db.Groups.Find(id);
            return View(document);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DocumentId,DocumentName,Description")] Document document)
        {
            if (ModelState.IsValid)
            {
                Document NewDocument = db.Documents.Find(document.DocumentId);
                NewDocument.DocumentName = document.DocumentName;
                NewDocument.Description = document.Description;

                db.Entry(NewDocument).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName", document.UploaderId);
            return View(document);
        }

        // GET: Documents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Document document = db.Documents.Find(id);
            db.Documents.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Download(int? id)
        {
            if (id == null)
            {
                return new
                HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);

            string path = Server.MapPath(document.FilePath);

            if (System.IO.File.Exists(path))
            {
                return File(path,
                MimeMapping.GetMimeMapping(document.FileName), document.FileName);
            }
            return HttpNotFound();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningManagementSystem/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;

namespace LearningManagementSystem.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Groups
        //[Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            return View(db.Groups.ToList());
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }
        public ActionResult GroupCourses(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Groups/Create
        //[Authorize(Roles = "Teacher")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[Authorize(Roles = "Teacher")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupId,GroupName,GroupDescription,GroupStart,GroupEnd")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: Groups/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit([Bind(Include = "GroupId,GroupName,GroupDescription,GroupStart,GroupEnd")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                //TempData["CurrentGroup"] = group.GroupId;
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: Groups/Delete/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [Authorize(Roles = "Teacher")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            string faultmessage = null;

            if ((group.Courses.Count() != 0) || (group.Users.Count() != 0)) {

                faultmessage = "Gruppen kan ej tas bort då den innehåller kopplingar till användare eller kurs.";

                TempData["Faultmessage"]=faultmessage;
                return RedirectToAction("Index");

               }
            else
       
           // try
            {
                db.Groups.Remove(group);
                db.SaveChanges();

                faultmessage = "Gruppen borttagen.";

                TempData["Faultmessage"] = faultmessage;
                return RedirectToAction("Index");
           }
            //catch
            //{
            //    return RedirectToAction("Faultydeleate");
            //}  
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningManagementSystem/Views/Documents/Create.cshtml
@model LearningManagementSystem.Models.Document

@{
    ViewBag.Title = "Create";
}

<h2>Upload</h2>

@using (Html.BeginForm("Create", "Documents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ladda upp dokument</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FilePath, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.Label("Dokument", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Document" name="Upload" />
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.UploaderId, "UploaderId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UploaderId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UploaderId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.UploadDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UploadDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UploadDate, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.GroupId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GroupId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CourseId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ActivityId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ActivityId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ActivityId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LearningManagementSystem/Views/Documents/Delete.cshtml
@model LearningManagementSystem.Models.Document

@{
    ViewBag.Title = "Delete";
}

<h2>Radera dokument</h2>


<div>
    <h4>Radera länk till uppladdat Dokument</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.DocumentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Uploader.FirstName)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        <dd>
            @Html.DisplayFor(model => model.Uploader.FirstName) @Html.DisplayFor(model => model.Uploader.LastName)
        </dd>
       
        @*<dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadDate)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.GroupId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GroupId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CourseId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CourseId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ActivityId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ActivityId)
            </dd>*@

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Radera" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Tillbaka", "Index")
        </div>
    }
</div>

LearningManagementSystem/Views/Documents/Details.cshtml
@model LearningManagementSystem.Models.Document

@{
    ViewBag.Title = "Details";
}

<div>
<h4>Dokumentdetaljer</h4>
<hr />
<dl class="dl-horizontal">
    
    <dt>
        @Html.DisplayNameFor(model => model.DocumentName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.DocumentName)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.FileName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.FileName)
   </dd>

    <dt>
    @*@Html.DisplayNameFor(model => model.Uploader.FirstName)*@
    @Html.Label("Uppladdat av")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Uploader.FirstName) @Html.DisplayFor(model => model.Uploader.LastName)
    </dd>

    
    @*<dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>*@

    <dt>
        @Html.DisplayNameFor(model => model.UploadDate)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.UploadDate)
    </dd>

    @*<dt>
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivityId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityId)
        </dd>*@

</dl>
</div>
<p>
    @Html.ActionLink("Redigera", "Edit", new { id = Model.DocumentId }) |
    @Html.ActionLink("Tillbaka", "Index")
</p>


       
      

 

LearningManagementSystem/Views/Documents/Index.cshtml
@model IEnumerable<LearningManagementSystem.Models.Document>

@{
    ViewBag.Title = "Index";
}

<h2>Dokument</h2>
<p>
    <input type="button" value="Ladda upp dokument" class="btn btn-default btn-primary" onclick=" location.href='@Url.Action("Create","Documents")' " />
</p>

@*<p>
        @Html.ActionLink("Ladda upp dokument", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DocumentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Uploader.FirstName) @Html.DisplayNameFor(model => model.Uploader.LastName)*@
            @Html.Label("Uppladdat av")
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilePath)
            </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.UploadDate)*@
            @Html.Label("Datum")
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.GroupId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActivityId)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            @*<td>
                    @Html.DisplayFor(modelItem => item.DocumentName)
                </td>*@
            <td>
                <a href="@item.FilePath">@Html.DisplayFor(modelItem => item.DocumentName)</a>
                @*<a href="~\Uploads\"+ @item.FileName> @Html.DisplayFor(modelItem => item.DocumentName)</a>
                    @Url.Action(item.)*@
                @*@Html.ActionLink(item.DocumentName,"Download", "Documents")*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uploader.FirstName) @Html.DisplayFor(modelItem => item.Uploader.LastName)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FilePath)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.UploadDate)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.GroupId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActivityId)
                </td>*@
            <td>
                @Html.ActionLink("Redigera", "Edit", new { id = item.DocumentId }) |
                @Html.ActionLink("Detaljer", "Details", new { id = item.DocumentId }) |
                @Html.ActionLink("Radera", "Delete", new { id = item.DocumentId })
            </td>
        </tr>
    }

</table>

<p>
    <input type="button" value="Administrera användare" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Account")' " />
    <input type="button" value="Administrera grupper" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Groups")' " />
    <input type="button" value="Administrera kurser" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Courses")' " />
    <input type="button" value="Administrera aktiviteter" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Activities")' " />
</p>