LearningManagementSystem/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;

namespace LearningManagementSystem.Controllers
{
    [Authorize]
    public class ActivitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Activities
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            var activities = db.Activities.Include(a => a.ActivityType).Include(a => a.Course); 
            return View(db.Activities.ToList());
        }

        // GET: Activities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: Activities/Create
        [Authorize(Roles = "Teacher")]
        public ActionResult Create()
        {
            ViewBag.ActivityTypeId = new SelectList(db.ActivityTypes, "ActivityTypeId", "ActivityTypeName");
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName");
            return View();
        }

        // POST: Activities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Create([Bind(Include = "ActivityId,ActivityName,ActivityDescription,ActivityStart,ActivityEnd,CourseId,ActivityTypeId")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Activities.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActivityTypeId = new SelectList(db.ActivityTypes, "ActivityTypeId", "ActivityTypeName", activity.ActivityTypeId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", activity.CourseId);
            return View(activity);
        }

        // GET: Activities/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActivityTypeId = new SelectList(db.ActivityTypes, "ActivityTypeId", "ActivityTypeName", activity.ActivityTypeId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", activity.CourseId);
            return View(activity);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit([Bind(Include = "ActivityId,ActivityName,ActivityDescription,ActivityStart,ActivityEnd,CourseId,ActivityTypeId")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(activity);
        }

        // GET: Activities/Delete/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activities.Find(id);
            db.Activities.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningManagementSystem/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;
using System.IO;

namespace LearningManagementSystem.Controllers
{
    [Authorize(Roles="Teacher")]
    public class DocumentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //private const string localUrl = @"~\Uploads\" ;
        private const string localUrl = @"\Uploads\";

        // GET: Documents
        public ActionResult Index()
        {
            var documents = db.Documents.Include(d => d.Uploader);
            return View(documents.ToList());
        }

        // GET: Documents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // GET: Documents/Create
        public ActionResult Create(int? GrId)
        {
            TempData["GroupId"] = GrId;
            ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DocumentId,DocumentName,Description,FileName,FilePath,UploaderId,UploadDate,GroupId,CourseId,ActivityId")] Document document, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                 
                var CurrentUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();
                if (CurrentUser.GroupId != null)
                {
                    document.GroupId = CurrentUser.GroupId;
                }
                else if (TempData["GroupId"] != null)
                {
                    document.GroupId = (int)TempData["GroupId"];
                }
                else
                {
                    document.GroupId = null;
                }

                if (upload != null && upload.ContentLength > 0)
                {
                    // Här sparas filen som ska laddas upp i vår katalog
                    string nameOfFile = System.IO.Path.GetFileName(upload.FileName);
                    string saveFilePath = Path.Combine((Server.MapPath(@"~\Uploads\")), nameOfFile);
                    upload.SaveAs(saveFilePath);

                    /// Här laddar vi dbset<Documents> med korrekta värden.
                    document.UploadDate = DateTime.Now;
                    document.FileName = nameOfFile;
                    document.FilePath = (@localUrl + nameOfFile);
                    document.UploaderId = CurrentUser.Id;
                    db.Documents.Add(document);
                    db.SaveChanges();
                    //return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }

            ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName", document.UploaderId, document.GroupId);
            return View(document);
        }


        // GET: Documents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            //ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName", document.UploaderId);
            //Group group = db.Groups.Find(id);
            return View(document);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DocumentId,DocumentName,Description")] Document document)
        {
            if (ModelState.IsValid)
            {
                Document NewDocument = db.Documents.Find(document.DocumentId);
                NewDocument.DocumentName = document.DocumentName;
                NewDocument.Description = document.Description;

                db.Entry(NewDocument).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UploaderId = new SelectList(db.Users, "Id", "FirstName", document.UploaderId);
            return View(document);
        }

        // GET: Documents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Document document = db.Documents.Find(id);
            db.Documents.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Download(int? id)
        {
            if (id == null)
            {
                return new
                HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);

            string path = Server.MapPath(document.FilePath);

            if (System.IO.File.Exists(path))
            {
                return File(path,
                MimeMapping.GetMimeMapping(document.FileName), document.FileName);
            }
            return HttpNotFound();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningManagementSystem/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;

namespace LearningManagementSystem.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Groups
        //[Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            return View(db.Groups.ToList());
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }
        public ActionResult GroupCourses(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Groups/Create
        //[Authorize(Roles = "Teacher")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[Authorize(Roles = "Teacher")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupId,GroupName,GroupDescription,GroupStart,GroupEnd")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: Groups/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit([Bind(Include = "GroupId,GroupName,GroupDescription,GroupStart,GroupEnd")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                //TempData["CurrentGroup"] = group.GroupId;
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: Groups/Delete/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [Authorize(Roles = "Teacher")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            string faultmessage = null;

            if ((group.Courses.Count() != 0) || (group.Users.Count() != 0)) {

                faultmessage = "Gruppen kan ej tas bort då den innehåller kopplingar till användare eller kurs.";

                TempData["Faultmessage"]=faultmessage;
                return RedirectToAction("Index");

               }
            else
       
           // try
            {
                db.Groups.Remove(group);
                db.SaveChanges();

                faultmessage = "Gruppen borttagen.";

                TempData["Faultmessage"] = faultmessage;
                return RedirectToAction("Index");
           }
            //catch
            //{
            //    return RedirectToAction("Faultydeleate");
            //}  
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningManagementSystem/Views/Groups/Create.cshtml
@model LearningManagementSystem.Models.Group

@{
    ViewBag.Title = "Create";
}

<h2>Grupp</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Skapa grupp</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           @Html.LabelFor(model => model.GroupDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupStart, new { htmlAttributes = new { @class = "form-control", placeholder="åååå-mm-dd"} })
                @Html.ValidationMessageFor(model => model.GroupStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupEnd, new { htmlAttributes = new { @class = "form-control", placeholder = "åååå-mm-dd" } })
                @Html.ValidationMessageFor(model => model.GroupEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LearningManagementSystem/Views/Groups/Delete.cshtml
@model LearningManagementSystem.Models.Group

@{
    ViewBag.Title = "Delete";
}

<h2>Grupp</h2>

@*<h3>Är du säker på att du vill radera gruppen?</h3>*@
<div>
    <h4>Radera grupp</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupEnd)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Radera" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Tillbaka", "Index")
        </div>
    }
</div>

LearningManagementSystem/Views/Groups/Details.cshtml
@model LearningManagementSystem.Models.Group

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.GroupName)</h2>

@*<h2>Grupp</h2>*@


<div>

    @*<h4>Gruppdetaljer</h4>*@
    <hr />

    <h4>@Html.DisplayFor(model => model.GroupDescription)</h4>

    <dl class="dl-horizontal">

        @*<dt>
                @Html.DisplayNameFor(model => model.GroupName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GroupName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GroupDescription)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GroupDescription)
            </dd>*@
    </dl>
    <dl>
        @Html.Label("Period: ")

        @Html.DisplayFor(model => model.GroupStart)

        @Html.DisplayFor(model => model.GroupEnd)
    </dl>
    <hr />
    <dl>
        <dd>
            <table class="table-condensed " style=" width:50% ">
                <tr>
                    <th>Gruppmedlemmar</th>
                    <th>E-mail</th>
                </tr>

                @foreach (var user in Model.Users)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => user.FirstName) @Html.DisplayFor(modelItem => user.LastName)</td>
                        <td>@Html.DisplayFor(modelItem => user.Email)</td>
                    </tr>
                }

            </table>
        </dd>
    </dl>
</div>
<div>
    <dl>
        <dd>
            @*<table class="table">
                    <tr>
                        <th>Dokument</th>
                    </tr>
                </table>
                <hr />
                @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <input type="file" name="file" />
                    <br>
                    <input type="submit" value="Ladda upp" />
                }*@
            @*@Html.ActionLink("Ladda upp dokument", "Create", "DocumentPaths", new { id = Model.GroupId }, new { @class = "btn btn-primary", @style = "color:white" })*@
            @*<hr />*@
            <hr />
            <table class="table-condensed" style=" width:50% ">
                <tr>
                    <th>
                    Dokument
                    </th>
                    <th>
                        Beskrivning
                    </th>
                    @*<th>
                    @Html.Label("Uppladdat av")
                </th>*@
                </tr>

                @foreach (var item in Model.Documents)
                {
                    <tr>
                        <td>
                            <a href="@item.FilePath">@Html.DisplayFor(modelItem => item.DocumentName)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.Uploader.FirstName) @Html.DisplayFor(modelItem => item.Uploader.LastName)
                    <td>*@
                    </tr>
                }

            </table>
        </dd>

    </dl>
</div>
<p>
    <div>

    </div>
    <div>
        <hr />
        @Html.ActionLink("Kurser för gruppen", "GroupCourses", "Groups", new { id = Model.GroupId }, new { @class = "btn btn-warning", @style = "color:white" })
        @*@Html.ActionLink("Användare", "Index", "Account", new { id = Model.GroupId }, new { @class = "btn btn-warning", @style = "color:white" })*@
    </div>
    <hr />

    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Teacher"))
        {
        <p>
            @Html.ActionLink("Redigera", "Edit", new { id = Model.GroupId }) |
            @Html.ActionLink("Tillbaka till grupplistan", "Index")
        </p>
        }
        @*else if (User.IsInRole("Student")) 
        {
            <p>
                @Html.ActionLink("Tillbaka", "Details")
            </p>
        }*@

     }
     
   @* @Html.ActionLink("Redigera", "Edit", new { id = Model.GroupId }) |*@
 

LearningManagementSystem/Views/Groups/Edit.cshtml
@model LearningManagementSystem.Models.Group

@{
    ViewBag.Title = "Edit";
}

<h2>Grupp</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Redigera grupp</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GroupId)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.GroupDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Lägg till dokument", "Create", "Documents", new { GrId = Model.GroupId }, new { @class = "btn btn-info", @style = "color:white margin-botton: 20px" }) <br><br>
                <input type="submit" value="Spara" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LearningManagementSystem/Views/Groups/Faultydelete.cshtml
@model IEnumerable<LearningManagementSystem.Models.Group>

@{
    ViewBag.Title = "Faultydelete";
}

<h2>Faultydelete</h2>

---------@{
    string message = "fel";
   
    {
        <div class="message">
            <p>@message</p>
        </div>
    }
}

LearningManagementSystem/Views/Groups/Index.cshtml
@model IEnumerable<LearningManagementSystem.Models.Group>

@{
    ViewBag.Title = "Index";
}

<h2>Grupper</h2>
<p>
    <input type="button" value="Skapa grupp" class="btn btn-default btn-primary" onclick=" location.href='@Url.Action("Create","Groups")' " />
</p>
<h4 class="text-danger"> @TempData["Faultmessage"]</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().GroupName)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.GroupDescription)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().GroupStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().GroupEnd)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.GroupDescription)
                </td>*@

            <td>
                @Html.DisplayFor(modelItem => item.GroupStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GroupEnd)
            </td>
            <td>
                @Html.ActionLink("Redigera", "Edit", new { id = item.GroupId }) |
                @Html.ActionLink("Detailjer", "Details", new { id = item.GroupId }) |
                @Html.ActionLink("Radera", "Delete", new { id = item.GroupId })
            </td>
        </tr>
    }
</table>

<p>
    <input type="button" value="Administrera användare" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Account")' " />
    <input type="button" value="Administrera kurser" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Courses")' " />
    <input type="button" value="Administrera aktiviteter" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Activities")' " />
    <input type="button" value="Administrera dokument" class="btn btn-default btn-info" onclick=" location.href='@Url.Action("Index","Documents")' " />
</p>